name: Bash with rtools org

on:
  push:
  #release
  #pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build wheel for cp${{ matrix.python }}-${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit Windows
          - os: windows-2019
            python: 37
            platform: win_amd64
          #- os: windows-2019
          #  python: 38
          #  platform: win_amd64
          #- os: windows-2019
          #  python: 39
          #  platform: win_amd64
          #- os: windows-2019
          #  python: 310
          #  platform: win_amd64
          #- os: windows-2019
          #  python: 311
          #  platform: win_amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup MSYS
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          path-type: inherit
          pacboy: >-
            cmake:p
            ninja:p

      - name: Install rtools 
        if: ${{ runner.os == 'Windows' }}
        run: |
          #choco install -y pkgconfiglite
          #choco install -y ninja
          choco install -y rtools
          
      - name: Tell distutils to use mingw (Windows)
        if: runner.os == 'Windows'
        #run: |
        #  $pydistutilsConfig = @"
        #  [build]
        #   compiler = mingw32"@
        #  $pydistutilsConfig | Out-File "$env:USERPROFILE\pydistutils.cfg" -Encoding UTF8
        run: |
           echo "[build]" > ~/pydistutils.cfg
           echo "compiler = mingw32" >> ~/pydistutils.cfg 
           echo "" >> ~/pydistutils.cfg 
           echo "[build_ext]" > ~/pydistutils.cfg
           echo "compiler = mingw32" >> ~/pydistutils.cfg 
           echo '==pydistutils.cfg=='
           cat ~/pydistutils.cfg
           echo '==================='
           #echo "[build]" | Out-File -Encoding ASCII ~/pydistutils.cfg
           #echo "compiler=mingw32" | Out-File -Encoding ASCII ~/pydistutils.cfg -Append
           #echo "[build]`ncompiler=mingw32"

      - name: Test cmake without python
        env: 
          FC: gfortran
        run: |
          echo '=============== ls /c/rtools43/x86_64-w64-mingw32.static.posix'
          ls /c/rtools43/x86_64-w64-mingw32.static.posix 
          export CMAKE_PREFIX_PATH="/c/msys64/mingw64/bin;/c/rtools43/x86_64-w64-mingw32.static.posix"
          export PATH=$PATH:/c/msys64/mingw64/bin:/c/rtools43/x86_64-w64-mingw32.static.posix/bin
          #export PATH=/c/rtools43/x86_64-w64-mingw32.static.posix/bin:$PATH
          ### echo 'which gfortran'
          ### which gfortran
          ### echo 'which cmake'
          ### which cmake
          ### echo 'which python'
          ### which python
          ### echo 'Looking for R-tools'
          ### ls /c/
          ### echo 'Looking in rtools43'
          ### ls /c/rtools43
          ### echo 'Looking in rtools43/ucrt64'
          ### ls /c/rtools43/ucrt64
          ### echo 'Looking in rtools43/ucrt64/bin'
          ### ls /c/rtools43/ucrt64/bin
          ### echo 'Looking in rtools43/ucrt64/lib'
          ### ls /c/rtools43/ucrt64/lib
          ### echo "FC=gfortran" >> $env:GITHUB_ENV
          ### echo "PLAT=x86_64" >> $env:GITHUB_ENV
          ### echo "MSYSTEM=UCRT64" >> $env:GITHUB_ENV
          ### echo 'ENV'
          ### env
          ### echo '=================================='
          ### echo 'Find gfortran'
          ### find /c/rtools43 -name "*gfortran*"
          ### echo 'Find blas'
          ### find /c/rtools43 -name "*blas*"
          ### echo '=================================='
          ### echo 'which gfortran'
          ### which gfortran
          ### echo 'which cmake'
          ### which cmake
          ### echo 'which python'
          ### which python
          export FC=gfortran
          export CC=gcc
          ### echo 'ls /'
          ### ls /
          ### echo 'ls /mingw64'
          ### ls /mingw64
          echo '=================================='
          cmake -S . -B mockbuild -DCMAKE_Fortran_COMPILER=/c/msys64/mingw64/bin/gfortran.exe
          #cmake -S . -B build -DCMAKE_PREFIX_PATH="/c/rtools43/x86_64-w64-mingw32.static.posix;/c/msys64/mingw64/bin"
          #cmake --build build
          
      - name: Test cmake with python
        run: |
          export CMAKE_PREFIX_PATH="/c/msys64/mingw64/bin;/c/rtools43/x86_64-w64-mingw32.static.posix"
          export PATH=/c/msys64/mingw64/bin:/c/rtools43/x86_64-w64-mingw32.static.posix/bin:$PATH
          export LD_LIBRARY_PATH=/c/msys64/mingw64/bin:/c/rtools43/x86_64-w64-mingw32.static.posix/lib:$LD_LIBRARY_PATH
          export LDFLAGS="-Wl,-rpath=."
          export NPY_DISTUTILS_APPEND_FLAGS=1
          export NPY_WINDOWS_GIT_ACTION_FIX=1
          echo '========================================='
          env
          echo '========================================='
          pip install setuptools wheel numpy>1.19 f90wrap
          FC=gfortran CC=gcc cmake -S . -B build -DBUILD_PYTHON=ON -G Ninja -DCMAKE_Fortran_COMPILER=/c/msys64/mingw64/bin/gfortran.exe
          cmake --build build -v
          
      - name: Build and test wheels
        uses: pypa/cibuildwheel@v2.14.0
        env:
          CIBW_ENVIRONMENT_WINDOWS: PATH="/c/rtools43/x86_64-w64-mingw32.static.posix/bin:$PATH" CMAKE_PREFIX_PATH="/c/rtools43/x86_64-w64-mingw32.static.posix" FC="gfortran" CC="gcc"
          CIBW_BUILD: cp${{ matrix.python }}-${{ matrix.platform }}

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl

  ### build_sdist:
  ###   name: Build source distribution
  ###   runs-on: ubuntu-latest

  ###   steps:
  ###     - name: Checkout repository
  ###       uses: actions/checkout@v3

  ###     - name: Setup Python
  ###       uses: actions/setup-python@v4
  ###       with:
  ###         python-version: 3.9

  ###     - name: Build source distribution
  ###       run: bash python/build_tools/build_sdist.sh

  ###     - name: Test source distribution
  ###       run: bash python/build_tools/test_sdist.sh

  ###     - name: Store artifacts
  ###       uses: actions/upload-artifact@v3
  ###       with:
  ###         path: dist/*.tar.gz

