name: Build binaries and python library on Windows (MSYS2+bash)

on:
  push:
  #release:
  #pull_request:
  #workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64, arch: x86_64 }
          #- { icon: '⬛', sys: mingw32, arch: i686 }
          #- { icon: '🟨', sys: ucrt64,  arch: x86_64  } # Experimental!
          #- { icon: '🟧', sys: clang64, arch: x86_64 } # Experimental!
    name: 🚧 ${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: bash
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2 gcc'
      if: ${{ matrix.sys != 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        pacboy: >-
          toolchain:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p
          
    - name: '${{ matrix.icon }} Setup MSYS2 clang'
      if: ${{ matrix.sys == 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        pacboy: >-
          toolchain:p
          flang:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p

    - name: Setup Python interpreter
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    #- name: '🚧 Verify environment before'
    #  run: |
    #    export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH
    #    echo "{PATH}={/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH}" >> "$GITHUB_ENV"
    #    echo '----PATH----'
    #    echo $PATH
    #    echo '----ENV----'
    #    env
    #    echo '---/mingw64----'
    #    ls /mingw64
    #    echo '---/mingw64/bin----'
    #    ls /mingw64/bin
    #    echo '---/c---''
    #    ls /c/
    #    echo '---/c/msys64/---''
    #    ls /c/msys64/
    #    echo '---/c/msys64/mingw64---'
    #    ls /c/msys64/mingw64/
    #    
    - name: '🚧 Verify environment without path'
      run: |
        #export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH
        echo '----PATH----'
        echo $PATH
        echo '----ENV----'
        env
        
    - name: '🚧 Verify environment with path'
      run: |
        #export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH
        export PATH=$(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        echo '----PATH----'
        echo $PATH
        echo '----ENV----'
        env
        
          
    - name: '🚧 Install python packages'
      run: |
        ${pythonLocation}/python -m ensurepip
        ${pythonLocation}/python -m pip install build wheel setuptools numpy
        echo "Python version"
        ${pythonLocation}/python --version
        
    #- name: '🚧 Overwrite directories'
    #  run: |
    #    ln -fsn /c/msys64/mingw64 /mingw64
    #    echo "     ls /mingw64    "
    #    ls -ltr /mingw64
    #    ln -fsn /c/msys64/mingw64/bin /c/ProgramData/Chocolatey/bin/
    #    echo "      ls  /c/CHoco   "
    #    ls -ltr /c/ProgramData/Chocolatey/bin/
    #    #cp /c/msys64/mingw64/bin/* /c/ProgramData/Chocolatey/bin/
        
          
    - name: '🚧 Build TOOL executable'
      run: |
        echo '--> which gfortran'
        which gfortran
        echo '--> which cmake'
        which cmake
        #export PATH=${pythonLocation}:/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH
        echo '===========> PATH'
        echo $PATH
        export PATH=$(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        echo '===========> PATH'
        echo $PATH
        echo '--> which gfortran'
        which gfortran
        echo '--> which cmake'
        which cmake
        FC=gfortran CC=cpp cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build 
        ls ./bin
        cp ./bin/sd.gfortran.exe ./bin/sd.gfortran.${{matrix.sys}}.${{matrix.arch}}.exe
        cp ./bin/sd.gfortran.exe ./bin/uppasd.${{matrix.sys}}.${{matrix.arch}}.exe
        ls ./bin
        
    - name: '🚧 Build TOOL python library'
      run: |
        export PATH=/c/msys64/mingw64/bin:/c/msys64/usr/bin:$PATH
        cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON
        cmake --build build 
        ls ./lib
        
    - uses: actions/upload-artifact@v3
      with:
       name: uppasd.${{matrix.sys}}.${{matrix.arch}}
       path: ./bin/uppasd*.exe
