name: Build binaries and python library on Windows (MSYS2+bash+venv)

on:
  push:
  #release:
  #pull_request:
  #workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '🟦', sys: mingw64, arch: x86_64 }
          #- { icon: '⬛', sys: mingw32, arch: i686 }
          #- { icon: '🟨', sys: ucrt64,  arch: x86_64  } # Experimental!
          #- { icon: '🟧', sys: clang64, arch: x86_64 } # Experimental!
    name: 🚧 ${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: bash
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2 gcc'
      if: ${{ matrix.sys != 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        release: false
        path-type: full
        pacboy: >-
          toolchain:p
          gcc-fortran:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p
          
    - name: '${{ matrix.icon }} Setup MSYS2 clang'
      if: ${{ matrix.sys == 'clang64' }}
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        release: false
        path-type: full
        pacboy: >-
          toolchain:p
          flang:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p

    - name: Setup Python interpreter
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: '🚧 Setup python environment' 
      run: |
        which python
        python -m ensurepip
        python -m pip install virtualenv
        python -m venv ~/build_env
        source ~/build_env/Scripts/activate
        python -m pip install build wheel setuptools numpy cibuildwheel 
        deactivate
        
    - name: '🚧 Add MSYS tools to path'
      run: |
        echo '-----Original github path--------'
        cat $GITHUB_PATH
        echo '------Action addition------------'
        #echo "$pythonLocation:/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin" > github_header
        echo "$(echo '$Python_ROOT_DIR' | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin" > github_header
        echo "$(echo '$Python_ROOT_DIR' | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin" 
        #echo $(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        paste github_header $GITHUB_PATH > $GITHUB_PATH
        echo '-----Final github path-----------'
        cat $GITHUB_PATH
          
    - name: '🚧 Build TOOL executable'
      #env:
      #  PATH: $pythonLocation:/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
      #  # env here does not expand dollar signs
      run: |
        echo '===========> PATH'
        echo $PATH
        echo '===========> ENV'
        env
        echo '===========> which gfortran'
        which gfortran
        echo '===========> which cmake'
        which cmake
        echo '===========> which python'
        which python
        export PATH=$(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        echo '===========> PATH'
        echo $PATH
        echo '===========> ENV'
        env
        echo '===========> which gfortran'
        which gfortran
        echo '===========> which cmake'
        which cmake
        echo '===========> which python'
        which python
        FC=gfortran CC=gcc cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build 
        ls ./bin
        cp ./bin/sd.gfortran.exe ./bin/sd.gfortran.${{matrix.sys}}.${{matrix.arch}}.exe
        cp ./bin/sd.gfortran.exe ./bin/uppasd.${{matrix.sys}}.${{matrix.arch}}.exe
        ls ./bin
        
    - name: '🚧 Build TOOL python library'
      #env: 
      #  PATH: $pythonLocation:/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
      run: |
        #echo '--> which gfortran'
        #which gfortran
        #echo '--> which cmake'
        #which cmake
        #echo '--> which python'
        #which python
        #export PATH=$pythonLocation:/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        export PATH=$(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        echo '===========> PATH'
        echo $PATH
        echo '===========> ENV'
        env
        source ~/build_env/Scripts/activate
        echo '--> which gfortran'
        which gfortran
        echo '--> which cmake'
        which cmake
        echo '--> which python'
        which python
        cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON
        cmake --build build 
        ls ./lib
        deactivate
        
    - name: '🚧 Build single wheel'
      run: |
        export PATH=$(echo "$Python_ROOT_DIR" | sed -E 's/^C:/\/c/; s/\\/\//g'):/c/msys64/${{matrix.sys}}/bin:/c/msys64/usr/bin:$PATH
        source ~/build_env/Scripts/activate
        rm -rf build
        python -m pip wheel . -vvv
        deactivate
        ls *.whl

    - uses: actions/upload-artifact@v3
      with:
       name: uppasd.${{matrix.sys}}.${{matrix.arch}}
       path: ./bin/uppasd*.exe
