name: Example CMake

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32, env: i686 }
          - { icon: '🟦', sys: mingw64, env: x86_64 }
          - { icon: '🟨', sys: ucrt64,  env: ucrt-x86_64  } # Experimental!
          - { icon: '🟧', sys: clang64, env: clang-x86_64 } # Experimental!
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make

        pacboy: >-
          toolchain:p
          openblas:p
          lapack:p
          fftw:p
          cmake:p
          ninja:p

    - name: '${{ matrix.icon }} Setup Fortran'
      if:  ${{matrix.env}} ! 'clang-x86_64'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          mingw-w64-${{matrix.env}}-gcc-fortran
          
    - name: '${{ matrix.icon }} Setup Flang'
      if:  ${{matrix.env}} == 'clang-x86_64'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          mingw-w64-${{matrix.env}}-flang
          
    - name: '🚧 Build TOOL'
      run: |
        cmake -S . -G Ninja -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build 
